services:
  - type: web
    name: yt-downloader
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "cd backend && gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 300"
    envVars:
      - key: FLASK_DEBUG
        value: "false"
